---
- hosts: lb
  become: true
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=yes

    - name: ensure nginx is runnig
      service: name=nginx state=started enabled=yes
